remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
sass:
  style: :compressed

repository: nhoughto/blog
permalink: pretty
prose:
  rooturl: '_posts'
  siteurl: 'http://nhoughto.github.io/blog/'
  media: 'media'
  metadata:
    _posts:
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "splash"
        field:
          element: "text"
          label: "Splash image"
          value: ""